### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Modnix#1]
## Ver 0.60 Preview
- [x] Implement setup.
- [x] Test PPDefMod compat.
- [x] Implement update checker.

## Ver 0.70 Preview
- [x] Implement mod meta parsing.
- [x] Improves and document troubleshoot.
- [x] Implement mod list and basic info.
- [x] Implement delete mod.

## Ver 0.80 Beta I
- [x] Remake icon.
- [x] Rename setup to installer to sort better in download list.
- [x] Allow operations in case of "both".
- [x] ~~Implement Harmony 1.2 bridge.~~ Did my best. Not working.
- [x] Open modnix location instead of launching directly.
- [x] Implement mod_info.js parsing.
- [x] Implement Phase.
- [x] Implement dynamic init parameter.
- [x] Implement game / modnix / ppml version checks.
- [x] PPML v0.2 compatibility.
- [x] Button icons.

## Ver 0.90 RC
- [x] Better Detect EPG path.
- [x] Full mod Info, not stub.
- [x] Implement add mod (dll).
- [x] Implement add mod (zip).
- [x] Implement add mod (7z).
- [x] ~~Ignore entry points with Obsolete attribute.~~ Leaving as a way for future loader to be backward compatible.
- [x] Deterministic mod loading.
- [x] Mod settings.
- [x] Switch Modnix to json based settings.
- [x] Auto game status refresh
- [x] Change setup game path
- [x] Change manager game path
- [x] PPDefModifier compatibility when adding mod.

## Ver 1.0
- [x] All-purpose mod interface.
- [x] Support resource mod_info (instead of embedded resources)
- [x] ~~Select newly added mods after add mod.~~ Not straight forward. Skipping.
- [x] Update Documentation.
- [x] Videos
- [x] Lots of testing.
