### ISSUE TITLE
Version 2.0 Roadmap

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Modnix#13]
~~A quick update to solve some pressing needs before the code is changed beyond recognition.~~

Well, there are more "pressing needs" than expected. More efficient to finish them and test.

- [x] Fix dll type instance sharing.
- [x] Add mod api action config_save.
- [x] Add mod api action assembly.
- [x] Implement game path api.
- [x] Allow mods to add to api. ~~Conflicts will ignore all.~~ First come first serve.
- [x] Add console log
- [x] Add change log.
- [x] Auto-refresh log.
- [x] Plain text log filter.
- [x] Warn when default config does not match new config.
- [x] Parse log for mod errors.
- [x] Parse console for mod errors.
- [x] Config editor.
- [x] Show release, license, unlicense, changelog, readme.
- [x] Enable / Disable mod.
- [x] Zip embedded libraries to reduce installer size.
- [x] Click on notice to jump to mod.
- [x] Mod priority.
- [x] Update PPML to v0.3.

Some more issues during testing:
- [x] Keep current selection on mod list refresh.
- [x] Show (dev) when on dev update channel.
- [x] Scan all game bar locations instead of relying on guid.
- [x] Auto-refresh mod list on loader log update.
- [x] Linkify game path.
- [x] Sort mod load order by phase.
- [x] Test mod notices with touch and stylus.
- [x] Linkify mod path.
- [x] Live json syntax validation for config.
- [x] List supporting docs in mod_info.
- [x] ~~Skip update check when on metered connection.~~ Too complicated outside of UWP.

**Comment by Sheep-y** [comment]
Some more issues during testing:
- [ ] Keep current selection on mod list refresh.
- [ ] Show (dev) when on dev update channel.
- [ ] Scan all game bar locations instead of relying on guid.
- [ ] Auto-refresh mod list on loader log update.

**Comment by Sheep-y** [comment]
Modnix 2 released on 2020-04-11.
