### ISSUE TITLE
Modnix 2.3 Roadmap

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Modnix#23]
GUI
- [x] Fix reset not updated after deleting config.
- [x] Ctrl+S in config editor
- [x] Home, End, Ins, and Del in mod list.
- [x] ~~Delete old mods, and note dups should be deleted.~~ Migrate config too? Overwrite? What about mod set? Too much for a minor update.
- [x] Tune down runtime warning notice.
- [x] Remember last app position.
- [x] Prompt result on manual check update.
- [x] Change log to monospace font.
- [x] Accept value output type for registered api, such as bool.

Common
- [x] Delete `JetBrains.Annotations.dll` if exists.
- [x] Rewrite File.ReadAllText and ReadAllLines with read only right to get around write lock.

Loader
- [x] Fix mod parser not using correct game version.
- [x] Apply mod priority config.

Api
- [x] Assembly/Assemblies api should support ppml.
- [x] Remember original (unwrapped) method.
- [x] Revise log loops.

**Comment by Tahvohck** [comment]
Suggestion while you're working on GUI changes: Change the log window to a monospace font. It's nice for logging utilities to be able to align their output.

**Comment by Sheep-y** [comment]
@Tahvohck Thanks for the suggestion. Done in 8832e9b3825f025d96002c2aeae37f8af2a71183 and d02fdc31c7ec919f6a480e3c723f91072785e29e and will land on next release.

**Comment by Sheep-y** [comment]
2.3 released on 2020-04-28.  Closing issue.
