### ISSUE TITLE
Action Mod Roadmap

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Modnix#26]
Planned for Modnix 3 (#23).

# Modnix 3 Beta 1
- [x] Expand mod_info to allow a Dictionary[] Actions field.
- [x] Implement framework to allow mods to process Actions. (let's call it `RunAction`).
- [x] Actions should add caller prefix to handler logger.
- [x] Hide duplicate load log.
- [x] All actions have Phase and OnError.

# Modnix 3 Beta 2
- [x] ~~Make configurable.~~ Pushed to Modnix 3.5 with config presets.
- [x] Allow API to find caller.  Required to use the correct session. Need to bound caller to thread since API is thread-safe.
- [x] The "Include" field runs Actions from another file, relative to the current file or absolute to the mod's folder.
- [x] Update PPDefModifier to support action through include.
- [x] ~~Allow action mod to load library.~~ Keep it simple. Between Modnix and Scripting Library, if a mod need something more it shouldn't be an action mod.
- [x] ~~Supports actions with the "Guid"/"Cls" field, and evaluates it like [PPDefModifier](https://github.com/tracktwo/ppdefmodifier/blob/master/PPDefModifier/PPDefModifier.cs).~~ PPDefModifier has been updated and there is no need to have its cake.

# Scripting Library Beta 1
- [x] A new mod bundled with Modnix.
- [x] Each mod have their own eval session, preserved between phases.
- [x] Provides the "eval.cs" api to evaluate c# code.
- [x] Provides the "pp.def" and "pp.defs" api for quick lookup of game def by guid, path, or type.
- [x] Supports actions with the "Eval" field, and evaluates the code on the fly.
- [x] Provide data cache for type/name/path.
- ~~Helpers to aid in modifying weapon, research, facility data.~~ Weapon done, the rest need more ideas.
- [x] Pre-load script evaluator in background.

# Scripting Library Beta 2
- [ ] A way to allow mod to add helpers.
- ~~[ ] Rewrite helpers to supports mod unload.~~ Things get messy when multiple mods modify the same data. No good fix I can see.
- [x] Use caller mod for API eval context.
- [ ] A helper to get tactical item with tag(s).
- [ ] Update dependent libraries.
- [ ] Try to solve the assembly reference issue again to avoid dll copying.

**Comment by Sheep-y** [comment]
Scripting Library no longer works, and I can't fix the dll conflicts.  Since all other tasks have been done, this tracker will now be closed.

It was nothing short of a miracle that it worked at all before.  Hopefully we can support some other kind of scripting in the future.  I am eyeing V8 integration, which should be a lot less messy in term of dlls.  It's been a pleasure, .Net Core, I will avoid you even more in the future.
